#!/bin/sh
# Coding Agent REPL launcher
# Set NO_COLOR=1 to disable ANSI colors
exec erl \
    -pa _build/default/lib/*/ebin \
    -pa _build/default/lib/coding_agent/ebin \
    -eval 'application:ensure_all_started(coding_agent), coding_agent_repl:start(), init:stop().' \
    -noshell
